---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node
  commands:
  - npm install

- name: build
  image: node
  commands:
  - npm run build

- name: test
  image: node
  commands:
  - npm test
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN

---
kind: signature
hmac: 4ca56c01a761701988d0a34242add4e6359ba421e99f0c157a84b00115da1082

...
