---
kind: pipeline
name: default

steps:
- name: install
  image: node
  commands:
  - npm install

- name: build
  image: node
  commands:
  - npm run build

- name: test
  image: node
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
  commands:
  - npm test
---
kind: signature
hmac: b7512881f0a39cd10f60ec54e753259efc08d07b76c9040977d76bab726114d9

...
